import { NextResponse } from "next/server"
import { cookies } from "next/headers"
import { validateOrigin } from "@/lib/csrf"

// POST /api/create-partner
// Headers upstream:
// - Authorization: SUPABASE_PROJECT_ANON_KEY (no Bearer)
// - Admin-Token: value from cookie/header (no Bearer)
export async function POST(req: Request) {
  try {
    // Origin validation for state-changing requests
    const originError = validateOrigin(req)
    if (originError) return originError

    // Validate request body size (1MB limit for partner creation)
    const contentLength = req.headers.get('content-length')
    if (contentLength) {
      const sizeInBytes = parseInt(contentLength, 10)
      const maxSizeBytes = 1 * 1024 * 1024 // 1MB
      if (sizeInBytes > maxSizeBytes) {
        return NextResponse.json({ error: "Request body too large. Maximum size is 1MB." }, { status: 413 })
      }
    }

    const { full_name, email, commission_percent } = (await req.json()) as {
      full_name?: string
      email?: string
      commission_percent?: number
    }

    // Password is autogenerated by the backend now, so we no longer accept or validate it here.
    if (!full_name || !email || typeof commission_percent !== "number") {
      return NextResponse.json({ error: "Missing required fields" }, { status: 400 })
    }

    const url =
      process.env.SUPABASE_CREATE_PARTNER_FUNCTION_URL

    const anon = process.env.SUPABASE_PROJECT_ANON_KEY || process.env.NEXT_PUBLIC_SUPABASE_PROJECT_ANON_KEY || ""
    if (!anon) {
      return NextResponse.json({ error: "Server not configured: missing SUPABASE_PROJECT_ANON_KEY" }, { status: 500 })
    }

  const cookieStore = await cookies()
  const cookieAdmin = cookieStore.get("admin-token")?.value
  // Support header override if present
  const headerAdmin = req.headers.get("Admin-Token") || req.headers.get("x-admin-token") || ""
  const adminToken = headerAdmin || cookieAdmin || ""

    if (!adminToken) {
      return NextResponse.json({ error: "Unauthorized: missing admin token" }, { status: 401 })
    }

    const upstream = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: anon,
        "Admin-Token": adminToken, // no Bearer prefix
      },
      // Do NOT send password - backend will autogenerate it
      body: JSON.stringify({ full_name, email, commission_percent }),
    })

    if (!upstream.ok) {
      try {
        const err = await upstream.json()
        // Backend returns error in err.error field, not err.message
        return NextResponse.json({ error: err?.error || "Failed to create partner" }, { status: upstream.status })
      } catch {
        return NextResponse.json({ error: "Failed to create partner" }, { status: upstream.status })
      }
    }

    const data = await upstream.json()
    // Expecting upstream to return: { message: "Partner <name> with Email - <email> has been created successfully" }
    return NextResponse.json(data)
  } catch (e) {
    return NextResponse.json({ error: "Unexpected server error" }, { status: 500 })
  }
}
