export default function AdminPartnersPage() {
  // Mock data for partner-specific metrics
  const partners = [
    {
      name: "Alex Carter",
      email: "alex@influencio.com",
      referrals: 128,
      conversions: 36,
      revenue: 12450,
    },
    {
      name: "Jordan Lee",
      email: "jordan@reachnow.io",
      referrals: 92,
      conversions: 18,
      revenue: 6150,
    },
    {
      name: "Sam Torres",
      email: "sam@sociallift.co",
      referrals: 210,
      conversions: 54,
      revenue: 18890,
    },
    {
      name: "Priya Kumar",
      email: "priya@convertly.ai",
      referrals: 77,
      conversions: 21,
      revenue: 8450,
    },
    {
      name: "Daniel Park",
      email: "daniel@flowwave.app",
      referrals: 156,
      conversions: 42,
      revenue: 15920,
    },
    {
      name: "Taylor Brooks",
      email: "taylor@refroute.io",
      referrals: 48,
      conversions: 9,
      revenue: 3020,
    },
  ]

  const currency = (n: number) =>
    new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(n)

  const rate = (conv: number, refs: number) => (refs ? `${Math.round((conv / refs) * 100)}%` : "0%")

  return (
    <section className="grid gap-4">
      <h1 className="text-xl md:text-2xl font-semibold text-pretty">Partner Performance</h1>
      <div className="border border-border rounded-lg p-6 bg-background overflow-hidden">
        <div className="mb-4">
          <h2 className="text-base md:text-lg font-medium">All Partners</h2>
          <p className="text-muted-foreground text-sm mt-1">
            Overview of referrals, conversions, and revenue generated by each partner.
          </p>
        </div>

        <div className="w-full overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="text-left text-muted-foreground">
                <th className="py-2 pr-4 font-medium">Partner</th>
                <th className="py-2 pr-4 font-medium">Email</th>
                <th className="py-2 pr-4 font-medium">Referrals</th>
                <th className="py-2 pr-4 font-medium">Conversions</th>
                <th className="py-2 pr-4 font-medium">Conversion Rate</th>
                <th className="py-2 pr-4 font-medium">Revenue</th>
              </tr>
            </thead>
            <tbody>
              {partners.map((inf) => (
                <tr key={inf.email} className="border-t border-border">
                  <td className="py-3 pr-4 whitespace-nowrap">{inf.name}</td>
                  <td className="py-3 pr-4 min-w-[220px] break-words">{inf.email}</td>
                  <td className="py-3 pr-4">{inf.referrals}</td>
                  <td className="py-3 pr-4">{inf.conversions}</td>
                  <td className="py-3 pr-4">{rate(inf.conversions, inf.referrals)}</td>
                  <td className="py-3 pr-4">{currency(inf.revenue)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </section>
  )
}
