import { NextResponse } from "next/server"
import { cookies } from "next/headers"
import { validateOrigin } from "@/lib/csrf"


export async function POST(req: Request) {
  try {
    // Origin validation for state-changing requests
    const originError = validateOrigin(req)
    if (originError) return originError

    // Validate request body size (1MB limit for admin creation)
    const contentLength = req.headers.get('content-length')
    if (contentLength) {
      const sizeInBytes = parseInt(contentLength, 10)
      const maxSizeBytes = 1 * 1024 * 1024 // 1MB
      if (sizeInBytes > maxSizeBytes) {
        return NextResponse.json({ error: "Request body too large. Maximum size is 1MB." }, { status: 413 })
      }
    }

    const body = await req.json()
    const { email, full_name, current_admin_password } = body as {
      email?: string
      full_name?: string
      current_admin_password?: string
    }

    // Basic validation - password is autogenerated by backend, no longer needed
    if (!email || !full_name || !current_admin_password) {
      return NextResponse.json({ error: "Missing required fields: email, full_name, current_admin_password" }, { status: 400 })
    }

    // Email validation
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      return NextResponse.json({ error: "Invalid email format" }, { status: 400 })
    }

    const url = process.env.SUPABASE_CREATE_ADMIN_FUNCTION_URL || "https://kyqtnxhgokczatymraxb.supabase.co/functions/v1/create-admin"

    const anon = process.env.SUPABASE_PROJECT_ANON_KEY || process.env.NEXT_PUBLIC_SUPABASE_PROJECT_ANON_KEY || ""
    if (!anon) {
      return NextResponse.json({ error: "Server not configured: missing SUPABASE_PROJECT_ANON_KEY" }, { status: 500 })
    }

    const cookieStore = await cookies()
    const adminToken = cookieStore.get("admin-token")?.value

    if (!adminToken) {
      return NextResponse.json({ error: "Unauthorized: missing admin token" }, { status: 401 })
    }

    const upstream = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: anon,
        "Admin-Token": adminToken,
      },
      // Do NOT send password - backend will autogenerate it
      body: JSON.stringify({
        email,
        full_name,
        current_admin_password
      }),
    })

    if (!upstream.ok) {
      try {
        const err = await upstream.json()
        // Backend returns error in err.error field, not err.message
        return NextResponse.json({ error: err?.error || "Failed to create admin" }, { status: upstream.status })
      } catch {
        return NextResponse.json({ error: "Failed to create admin" }, { status: upstream.status })
      }
    }

    const data = await upstream.json()
    return NextResponse.json(data)
  } catch (e) {
    return NextResponse.json({ error: "Unexpected server error" }, { status: 500 })
  }
}
